version: '3.8'

services:
  api:
    # image: johncons/chat-bot-api:latest
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data/sqlite:/data/sqlite
    environment:
      - DATABASE_URL=sqlite:///data/sqlite/agent.db
      - PORT=8080
